# func_print_head "Install Python36" 
#   yum install python36 gcc python3-devel -y &>>$log_file
#   func_status_check $?

#   func_app_prereq

#   func_print_head "Install Python Dependencies" 
#   pip3.6 install -r requirements.txt &>>$log_file
#   func_status_check $?
  
#   func_print_head "Update Password in System Service File"
#   sed -i -e "s|rabbitmq_appuser_password|${rabbitmq_appuser_password}|" ${script_path}/${component}.service &>>$log_file
#   func_status_check $?
  
#   func_systemd_setup

- name: Install python36
  ansible.builtin.shell: yum install python36 gcc python3-devel

# - name: Install Python36
#   ansible.builtin.yum:
#     name: python36; gcc; python3-devel
#     state: installed

- name: Include App Prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install python36
  ansible.builtin.shell: pip3.6 install -r requirements.txt

- name: hi
  ansible.builtin.shell: sed -i -e "s|rabbitmq_appuser_password|${rabbitmq_appuser_password}|" ${script_path}/${component}.service

- name: Include SystemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml  