
# - name: Install python36
#   ansible.builtin.shell: yum install python36 gcc python3-devel

- name: Install Python36
  ansible.builtin.yum:
    name: 
      - python36 
      - gcc 
      - python3-devel
    state: installed

- name: Include App Prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install Python Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Include Schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include SystemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml  